plugins {
    id 'java'
    id 'application'
}

group = 'com.bulgumtong'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = 'com.bulgumtong.Main'
}

repositories { mavenCentral() }

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

test { useJUnitPlatform() }
